#ifndef COMMANDS_H
#define COMMANDS_H

#define COMMAND_CONSTANT_VOLTAGE	1
#define COMMAND_CONSTANT_CURRENT 	2
#define COMMAND_CONSTANT_SPEED_ENCODER 	3
#define COMMAND_CONSTANT_POSITION	4
#define COMMAND_EDIT_KP			5
#define COMMAND_EDIT_KI			6
#define COMMAND_EDIT_KD			7
#define COMMAND_EDIT_OUTPUT_DIVISOR	8
#define COMMAND_GET_CURRENT		9
#define COMMAND_GET_SPEED		10
#define COMMAND_GET_POSITION		11
#define COMMAND_IDLE			12

#endif
