# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copy-headers
### Generated for copy rule.
$(builddir)/include/ccore_bson_static.h: TOOLSET := $(TOOLSET)
$(builddir)/include/ccore_bson_static.h: ../../../ccore_cpp/include/ccore_bson_static.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/ccore_bson_static.h
$(builddir)/include/ccore_libbson.h: TOOLSET := $(TOOLSET)
$(builddir)/include/ccore_libbson.h: ../../../ccore_cpp/include/ccore_libbson.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/ccore_libbson.h
$(builddir)/include/ccore_poll_libbson.h: TOOLSET := $(TOOLSET)
$(builddir)/include/ccore_poll_libbson.h: ../../../ccore_cpp/include/ccore_poll_libbson.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/ccore_poll_libbson.h
$(builddir)/include/ccore_msg_libbson.h: TOOLSET := $(TOOLSET)
$(builddir)/include/ccore_msg_libbson.h: ../../../ccore_cpp/include/ccore_msg_libbson.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/ccore_msg_libbson.h
$(builddir)/include/ccore_common.h: TOOLSET := $(TOOLSET)
$(builddir)/include/ccore_common.h: ../../../ccore_lib/include/ccore_common.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/ccore_common.h
$(builddir)/include/ccore.h: TOOLSET := $(TOOLSET)
$(builddir)/include/ccore.h: ../../../ccore_lib/include/ccore.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/ccore.h
$(builddir)/include/ccore_poll.h: TOOLSET := $(TOOLSET)
$(builddir)/include/ccore_poll.h: ../../../ccore_lib/include/ccore_poll.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/ccore_poll.h
$(builddir)/include/bson.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson.h: ../../../ccore_bson/ccore_bson/include/bson.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson.h
$(builddir)/include/document.h: TOOLSET := $(TOOLSET)
$(builddir)/include/document.h: ../../../ccore_bson/ccore_bson/include/document.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/document.h
$(builddir)/include/element.h: TOOLSET := $(TOOLSET)
$(builddir)/include/element.h: ../../../ccore_bson/ccore_bson/include/element.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/element.h
$(builddir)/include/serializable.h: TOOLSET := $(TOOLSET)
$(builddir)/include/serializable.h: ../../../ccore_bson/ccore_bson/include/serializable.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/serializable.h
$(builddir)/include/shared_buffer.h: TOOLSET := $(TOOLSET)
$(builddir)/include/shared_buffer.h: ../../../ccore_bson/ccore_bson/include/shared_buffer.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/shared_buffer.h
$(builddir)/include/typelist.h: TOOLSET := $(TOOLSET)
$(builddir)/include/typelist.h: ../../../ccore_bson/ccore_bson/include/typelist.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/typelist.h
_________ccore_cpp_builds_gyp_project_gyp_copy_headers_target_copies = $(builddir)/include/ccore_bson_static.h $(builddir)/include/ccore_libbson.h $(builddir)/include/ccore_poll_libbson.h $(builddir)/include/ccore_msg_libbson.h $(builddir)/include/ccore_common.h $(builddir)/include/ccore.h $(builddir)/include/ccore_poll.h $(builddir)/include/bson.h $(builddir)/include/document.h $(builddir)/include/element.h $(builddir)/include/serializable.h $(builddir)/include/shared_buffer.h $(builddir)/include/typelist.h

### Rules for final target.
# Build our special outputs first.
$(obj).target/../../../ccore_cpp/builds/gyp/copy-headers.stamp: | $(_________ccore_cpp_builds_gyp_project_gyp_copy_headers_target_copies)

# Preserve order dependency of special output on deps.
$(_________ccore_cpp_builds_gyp_project_gyp_copy_headers_target_copies): | $(obj).target/../../../ccore_lib/builds/gyp/libccore.a $(obj).target/../../../ccore_bson/builds/gyp/libccore_bson.a $(obj).target/../../../libbson/builds/gyp/libbson.a

$(obj).target/../../../ccore_cpp/builds/gyp/copy-headers.stamp: TOOLSET := $(TOOLSET)
$(obj).target/../../../ccore_cpp/builds/gyp/copy-headers.stamp: $(obj).target/../../../ccore_lib/builds/gyp/libccore.a $(obj).target/../../../ccore_bson/builds/gyp/libccore_bson.a $(obj).target/../../../libbson/builds/gyp/libbson.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/../../../ccore_cpp/builds/gyp/copy-headers.stamp
# Add target alias
.PHONY: copy-headers
copy-headers: $(obj).target/../../../ccore_cpp/builds/gyp/copy-headers.stamp

