# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copy-bson-headers
### Generated for copy rule.
$(builddir)/include/bson/b64_ntop.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/b64_ntop.h: ../../../libbson/src/bson/b64_ntop.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/b64_ntop.h
$(builddir)/include/bson/b64_pton.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/b64_pton.h: ../../../libbson/src/bson/b64_pton.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/b64_pton.h
$(builddir)/include/bson/bcon.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bcon.h: ../../../libbson/src/bson/bcon.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bcon.h
$(builddir)/include/bson/bson-atomic.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-atomic.h: ../../../libbson/src/bson/bson-atomic.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-atomic.h
$(builddir)/include/bson/bson-clock.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-clock.h: ../../../libbson/src/bson/bson-clock.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-clock.h
$(builddir)/include/bson/bson-compat.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-compat.h: ../../../libbson/src/bson/bson-compat.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-compat.h
$(builddir)/include/bson/bson-context-private.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-context-private.h: ../../../libbson/src/bson/bson-context-private.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-context-private.h
$(builddir)/include/bson/bson-context.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-context.h: ../../../libbson/src/bson/bson-context.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-context.h
$(builddir)/include/bson/bson-decimal128.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-decimal128.h: ../../../libbson/src/bson/bson-decimal128.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-decimal128.h
$(builddir)/include/bson/bson-endian.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-endian.h: ../../../libbson/src/bson/bson-endian.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-endian.h
$(builddir)/include/bson/bson-error.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-error.h: ../../../libbson/src/bson/bson-error.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-error.h
$(builddir)/include/bson/bson-iso8601-private.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-iso8601-private.h: ../../../libbson/src/bson/bson-iso8601-private.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-iso8601-private.h
$(builddir)/include/bson/bson-iter.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-iter.h: ../../../libbson/src/bson/bson-iter.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-iter.h
$(builddir)/include/bson/bson-json.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-json.h: ../../../libbson/src/bson/bson-json.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-json.h
$(builddir)/include/bson/bson-keys.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-keys.h: ../../../libbson/src/bson/bson-keys.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-keys.h
$(builddir)/include/bson/bson-macros.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-macros.h: ../../../libbson/src/bson/bson-macros.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-macros.h
$(builddir)/include/bson/bson-md5.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-md5.h: ../../../libbson/src/bson/bson-md5.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-md5.h
$(builddir)/include/bson/bson-memory.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-memory.h: ../../../libbson/src/bson/bson-memory.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-memory.h
$(builddir)/include/bson/bson-oid.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-oid.h: ../../../libbson/src/bson/bson-oid.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-oid.h
$(builddir)/include/bson/bson-private.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-private.h: ../../../libbson/src/bson/bson-private.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-private.h
$(builddir)/include/bson/bson-reader.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-reader.h: ../../../libbson/src/bson/bson-reader.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-reader.h
$(builddir)/include/bson/bson-stdint-win32.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-stdint-win32.h: ../../../libbson/src/bson/bson-stdint-win32.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-stdint-win32.h
$(builddir)/include/bson/bson-string.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-string.h: ../../../libbson/src/bson/bson-string.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-string.h
$(builddir)/include/bson/bson-thread-private.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-thread-private.h: ../../../libbson/src/bson/bson-thread-private.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-thread-private.h
$(builddir)/include/bson/bson-timegm-private.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-timegm-private.h: ../../../libbson/src/bson/bson-timegm-private.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-timegm-private.h
$(builddir)/include/bson/bson-types.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-types.h: ../../../libbson/src/bson/bson-types.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-types.h
$(builddir)/include/bson/bson-utf8.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-utf8.h: ../../../libbson/src/bson/bson-utf8.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-utf8.h
$(builddir)/include/bson/bson-value.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-value.h: ../../../libbson/src/bson/bson-value.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-value.h
$(builddir)/include/bson/bson-version-functions.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-version-functions.h: ../../../libbson/src/bson/bson-version-functions.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-version-functions.h
$(builddir)/include/bson/bson-writer.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-writer.h: ../../../libbson/src/bson/bson-writer.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-writer.h
$(builddir)/include/bson/bson.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson.h: ../../../libbson/src/bson/bson.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson.h
$(builddir)/include/bson/bson-config.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-config.h: ../../../libbson/builds/gyp/linux/bson-config.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-config.h
$(builddir)/include/bson/bson-stdint.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-stdint.h: ../../../libbson/builds/gyp/linux/bson-stdint.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-stdint.h
$(builddir)/include/bson/bson-version.h: TOOLSET := $(TOOLSET)
$(builddir)/include/bson/bson-version.h: ../../../libbson/builds/gyp/linux/bson-version.h FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/include/bson/bson-version.h
_________ccore_cpp_builds_gyp_project_gyp_copy_bson_headers_target_copies = $(builddir)/include/bson/b64_ntop.h $(builddir)/include/bson/b64_pton.h $(builddir)/include/bson/bcon.h $(builddir)/include/bson/bson-atomic.h $(builddir)/include/bson/bson-clock.h $(builddir)/include/bson/bson-compat.h $(builddir)/include/bson/bson-context-private.h $(builddir)/include/bson/bson-context.h $(builddir)/include/bson/bson-decimal128.h $(builddir)/include/bson/bson-endian.h $(builddir)/include/bson/bson-error.h $(builddir)/include/bson/bson-iso8601-private.h $(builddir)/include/bson/bson-iter.h $(builddir)/include/bson/bson-json.h $(builddir)/include/bson/bson-keys.h $(builddir)/include/bson/bson-macros.h $(builddir)/include/bson/bson-md5.h $(builddir)/include/bson/bson-memory.h $(builddir)/include/bson/bson-oid.h $(builddir)/include/bson/bson-private.h $(builddir)/include/bson/bson-reader.h $(builddir)/include/bson/bson-stdint-win32.h $(builddir)/include/bson/bson-string.h $(builddir)/include/bson/bson-thread-private.h $(builddir)/include/bson/bson-timegm-private.h $(builddir)/include/bson/bson-types.h $(builddir)/include/bson/bson-utf8.h $(builddir)/include/bson/bson-value.h $(builddir)/include/bson/bson-version-functions.h $(builddir)/include/bson/bson-writer.h $(builddir)/include/bson/bson.h $(builddir)/include/bson/bson-config.h $(builddir)/include/bson/bson-stdint.h $(builddir)/include/bson/bson-version.h

### Rules for final target.
# Build our special outputs first.
$(obj).target/../../../ccore_cpp/builds/gyp/copy-bson-headers.stamp: | $(_________ccore_cpp_builds_gyp_project_gyp_copy_bson_headers_target_copies)

# Preserve order dependency of special output on deps.
$(_________ccore_cpp_builds_gyp_project_gyp_copy_bson_headers_target_copies): | $(obj).target/../../../ccore_lib/builds/gyp/libccore.a $(obj).target/../../../ccore_bson/builds/gyp/libccore_bson.a $(obj).target/../../../libbson/builds/gyp/libbson.a

$(obj).target/../../../ccore_cpp/builds/gyp/copy-bson-headers.stamp: TOOLSET := $(TOOLSET)
$(obj).target/../../../ccore_cpp/builds/gyp/copy-bson-headers.stamp: $(obj).target/../../../ccore_lib/builds/gyp/libccore.a $(obj).target/../../../ccore_bson/builds/gyp/libccore_bson.a $(obj).target/../../../libbson/builds/gyp/libbson.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/../../../ccore_cpp/builds/gyp/copy-bson-headers.stamp
# Add target alias
.PHONY: copy-bson-headers
copy-bson-headers: $(obj).target/../../../ccore_cpp/builds/gyp/copy-bson-headers.stamp

