# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := ccore_cpp
DEFS_Default := \
	'-DCCORE_CPP_GYP_BUILD' \
	'-DCCORE_CPP_HAVE_LINUX' \
	'-DCCORE_STATIC' \
	'-DZMQ_STATIC' \
	'-DCZMQ_STATIC' \
	'-DZMQ_BUILD_DRAFT_API' \
	'-DCZMQ_BUILD_DRAFT_API'

# Flags passed to all source files.
CFLAGS_Default :=

# Flags passed to only C files.
CFLAGS_C_Default :=

# Flags passed to only C++ files.
CFLAGS_CC_Default := \
	-std=c++11

INCS_Default := \
	-I../../../ccore_cpp/include \
	-I../../../ccore_cpp/builds/gyp \
	-I../../../ccore_lib/include \
	-I../../../libzmq/include \
	-I../../../czmq/include \
	-I../../../ccore_bson/ccore_bson/include \
	-I../../../libbson/src \
	-I../../../libbson/builds/gyp/linux

OBJS := \
	$(obj).target/$(TARGET)/../../../ccore_cpp/src/ccore.o \
	$(obj).target/$(TARGET)/../../../ccore_cpp/src/ccore_poll.o \
	$(obj).target/$(TARGET)/../../../ccore_cpp/src/ccore_msg.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default :=

LIBS := \
	-lpthread

$(obj).target/../../../ccore_cpp/builds/gyp/libccore_cpp.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/../../../ccore_cpp/builds/gyp/libccore_cpp.a: LIBS := $(LIBS)
$(obj).target/../../../ccore_cpp/builds/gyp/libccore_cpp.a: TOOLSET := $(TOOLSET)
$(obj).target/../../../ccore_cpp/builds/gyp/libccore_cpp.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/../../../ccore_cpp/builds/gyp/libccore_cpp.a
# Add target alias
.PHONY: ccore_cpp
ccore_cpp: $(obj).target/../../../ccore_cpp/builds/gyp/libccore_cpp.a

# Add target alias to "all" target.
.PHONY: all
all: ccore_cpp

