#ifndef COMMANDS_H
#define COMMANDS_H

#define COMMAND_SET_INPUT_PULLDOWN_MODE 1
#define COMMAND_SET_INPUT_PULLUP_MODE 2
#define COMMAND_SET_INPUT_FLOATING_MODE 3
#define COMMAND_SET_OUTPUT_MODE 4
#define COMMAND_SET_OUTPUT_DATA 5
#define COMMAND_GET_INPUT_DATA 6

#endif
